### ISSUE TITLE
[User Story] Implement APScheduler-based daemon/processor

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#507] opened 2018-11-07 19:27 UTC
We had a vote on how to move forward with our processor daemons and agreed to migrate over to ApScheduler. Currently, the only scheduled coroutine solution we have in place is Tornado. ApScheduler was chosen for its focus on job scheduling (tornado also contains webserver capabilities). Priorities have shifted, so this task is backlogged for now.

Implement a POC listener based on APScheduler (replace tornado?)

**Comment by PatrickLammers** [comment] 2019-01-02 22:31
@kthblmfld Let's discuss the pros & cons of this change...  do we really need it for the first release?

**Comment by PatrickLammers** [comment] 2019-01-09 23:10
related to #464 -- needed for PP?

**Comment by PatrickLammers** [comment] 2019-03-27 20:05
duplicate of tmobile\sawtooth-next-directory 119

**Closed by PatrickLammers** 2019-03-27 20:05 UTC
Labels: NEXT Directory, Prod Parallel, requirements, technical debt
