### ISSUE TITLE
[Epic] Bi-Directional Active Directory (LDAP) Sync

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#326] opened 2018-10-22 16:55 UTC
Create a toggleable sync module that, when active, syncs org data between Active Directory and NEXT using LDAP.

**Comment by kthblmfld** [comment] 2018-10-22 20:29
Closing this since it is a duplicate of #50

**Comment by jbobo** [comment] 2018-11-13 22:41
Accidentally reopened. Closing as it's a duplicate of #50

**Closed by jbobo** 2018-11-13 22:41 UTC
Labels: Epic, NEXT Directory, duplicate
