### ISSUE TITLE
[Bug] UI does not give feedback if user can't login

### ISSUE THREAD

**Issue by nadiabahrami** [hyperledger/sawtooth-next-directory#908] opened 2018-12-27 16:35 UTC
Bug  | UI does not give feedback if the user can't login
----------|----------
Description | Currently when someone tries to login and can't the UI breaks.   The user should have feedback that the login has failed for whatever reason.

![Screen Shot 2018-12-27 at 8.33.12 AM.png](https://images.zenhubusercontent.com/575921babf93871ccd9c5898/2485afd8-ec06-450d-a673-f15bedeb0054)

**Comment by PatrickLammers** [comment] 2019-01-23 18:59
Seems like a duplicate of #75 too

**Closed** 2019-01-31 21:21 UTC
Labels: NEXT UI, bug
