### ISSUE TITLE
Add Swagger UI to the project

### ISSUE THREAD

**Issue by kthblmfld** [hyperledger/sawtooth-next-directory#352] opened 2018-10-25 01:36 UTC
The project has an openapi document that has been manually maintained over time.

It will need Swagger pages that deploy along with the rest-api per future integration plans within the TMO services ecosystem ( Integration with Clearwater repo )

Compare a few options and implement the most well-maintained, user-friendly solution.

A few to options to start looking into:
https://pypi.org/project/sanic-swagger/
https://pypi.org/project/sanic-attrs/

**Comment by PatrickLammers** [comment] 2018-12-27 20:32
duplicate of #869??

**Comment by satkeeva** [comment] 2018-12-28 18:44
I am working on #869 which appears to be a duplicate of #352. Closing #352 since #869 is in progress

**Closed by satkeeva** 2018-12-28 18:44 UTC
Labels: Infra, NEXT API, requirements
