### ISSUE TITLE
[User Story] Unique Usernames

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#135] opened 2018-09-24 22:07 UTC
User Story | Username uniqueness
----------|----------
T-shirt size: | L
User Story | Application should enforce unique usernames for accts created through NeXt.  
Details | Previous version of the application required login via the user's UUID.
Acceptance Criteria/Tests |  Enforce **unique** usernames across the system, usernames are NOT case sensitive, 
Definition of Done | Passes all regression tests, Passes testing per acceptance criteria, Approved by UI team, Able to show feature in demo                                                                                                    
Dependencies | #134 #386 

PR #13  added support for usernames, however the code was not fully baked.

**Comment by PatrickLammers** [comment] 2019-02-15 22:30
reactivating this one since it doesn't seem we have met the **unique** requirement yet.

**Comment by PatrickLammers** [comment] 2019-03-11 22:13
#1331 is a duplicate of this...

**Closed by PatrickLammers** 2019-03-11 22:13 UTC
Labels: enhancement
