### ISSUE TITLE
Host Swagger 

### ISSUE THREAD

**Issue by satkeeva** [hyperledger/sawtooth-next-directory#869] opened 2018-12-19 21:54 UTC
[User Story] [Epic] | Host Swagger on dev server
----------|----------
Epic Title | 
User Story Title | Host Swagger on dev server
T-shirt size: S(mall), M(edium), L(arge) | M
User Story | [Value Statement] "As a contributor I would like to see how different APIs and functionalities work"
Description |  Capability to view Swagger

**Comment by PatrickLammers** [comment] 2018-12-27 20:32
Is this a duplicate of issue 352? If so, please close that one too.

**Closed** 2019-01-07 21:05 UTC
Labels: NEXT API
