### ISSUE TITLE
S2 [Task] Stabilize Master Branch

### ISSUE THREAD

**Issue by agoldingay** [hyperledger/sawtooth-next-directory#100] opened 2018-09-17 23:09 UTC
High priority item discussed through 9/17/18 Sprint planning meeting for dev9 team.

Issue | Stabilize Develop Branch
----------|----------
T-shirt size: S(mall), M(edium), L(arge) | M
Story Points - Fibonacci (1,2,3,5,8,13) | 3
Description | There are a number of issues around this task (#56, #57, #47, #108, #45, #46, #21, #23, #20) The high-level goal is to have a consistently stable codebase that deploys successfully on checkout, includes up-to-date documentation, and behaves as expected (few/no misleading errors or timeouts).

**Comment by kthblmfld** [comment] 2018-09-20 01:05
We need to have the discussion about whether now is a good time to continue with the develop branch or not.

As far as the primary cause of recent instability is concerned: The change to Sanic version is in master and the app starts up as expected. 

There are additional stability-related matters under investigation, but those will require their own stories and tasks as the root causes are identified and/or symptoms are easily reproduced via step-by-step instructions.

**Comment by agoldingay** [comment] 2018-09-20 15:47
@chrisspanton @devsatishm this is a blocker. Need a decision on how to move forward. This is a S2 commitment. Please advise.

**Comment by kthblmfld** [comment] 2018-09-27 18:09
Moving this to Done because the master branch is considerably more stable than it was when this task was opened, and the need to "Stabilize master branch" will/should henceforth be carried out within minutes/hours as new breakages occur.

**Closed** 2018-10-13 04:14 UTC
Labels: enhancement
