### ISSUE TITLE
[User Story] Secure Environment Variable Providers

### ISSUE THREAD

**Issue by adamgering** [hyperledger/sawtooth-next-directory#590] opened 2018-11-15 23:33 UTC
[User Story] | Secure Environment Variable Providers
----------|----------
Epic Title | 
User Story Title | Secure Environment Variable Providers
T-shirt size: S(mall), M(edium), L(arge) | M
Story Points - Fibonacci (1,2,3,5,8,13) | 5
User Story | Secure Environment Variable Providers
Description | Add support for secure environment variable providers (e.g. TVAULT) in the common configuration helper class (#589).
Business Need (the why): | 
Details | 
Additional User Story | #589
Dependencies | #589
Assumptions | 
Questions/Clarifications |

**Comment by PatrickLammers** [comment] 2018-12-31 23:54
@adamgering  Can we write this as user story?  It helps to explain what adding this to the product means to the user -- what functionality is enabled by this?  It would really help us figure out the priority

**Comment by PatrickLammers** [comment] 2019-03-26 22:17
pretty sure this a duplicate of #206 -- at least without more details.

**Closed by PatrickLammers** 2019-03-26 22:17 UTC
